# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
