# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 03:54
from __future__ import unicode_literals

import api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='\u6807\u9898', max_length=128)),
                ('content', models.TextField(help_text='\u5185\u5bb9')),
                ('click', models.IntegerField(null=True)),
                ('created_at', api.fields.CreatedDateTimeField(null=True)),
                ('updated_at', api.fields.UpdatedDateTimeField(null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='\u8bc4\u8bba')),
                ('created_at', api.fields.CreatedDateTimeField(null=True)),
                ('blog', models.ForeignKey(help_text='\u88ab\u8bc4\u8bba\u7684\u535a\u5ba2', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='api.Blog')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('created_at', api.fields.CreatedDateTimeField(null=True)),
                ('updated_at', api.fields.UpdatedDateTimeField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='\u8bc4\u8bba\u8005', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='api.User'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(help_text='\u4f5c\u8005', on_delete=django.db.models.deletion.CASCADE, related_name='user_blogs', to='api.User'),
        ),
    ]
