# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwin', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwprd',
            new_name='password',
        ),
    ]
